replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: arm32v7-latest # ARM image
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: LoadBalancer
  port: 80

volumes:
  - name: sonarr-config
    persistentVolumeClaim:
      claimName: "sonarr-config-pvc" # PersistentVolumeClaim created earlier
  - name: sonarr-tv-shows
    nfs:
      path: "/volume1/TV Shows"
      server: 192.168.1.111
  - name: sonarr-downloads
    nfs:
      path: "/volume1/Storage/downloads"
      server: 192.168.1.111

volumeMounts:
  - name: sonarr-config
    mountPath: "/config"
    subPath: "configs/sonarr" # Path /mnt/ssd/media/configs/sonarr where sonarr writes the configuration
  - name: sonarr-tv-shows
    mountPath: "/tv-shows"
  - name: sonarr-downloads
    mountPath: "/downloads"
