apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "media-nfs"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "30Gi"