kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-config-pvc
  namespace: "media"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
